"""SO-101 (SO-ARM101) real-robot environment for MPAIL."""

from .robot_limits import (
    ACTION_DIM,
    CONTROL_FREQUENCY_HZ,
    DEFAULT_ROBOT_HOST,
    DEFAULT_ROBOT_PORT,
    HOME_EE_M,
    HOME_GRIPPER_DEG,
    HOME_POSITION_DEG,
    EE_HALF_RANGE_M,
    EE_LOWER_M,
    EE_UPPER_M,
    GRIPPER_HALF_RANGE,
    GRIPPER_LOWER_DEG,
    GRIPPER_UPPER_DEG,
    JOINT_LOWER_DEG,
    JOINT_NAMES,
    JOINT_UPPER_DEG,
    MAX_DELTA_DEG,
    MAX_DELTA_M,
    MAX_EPISODE_STEPS,
    STATE_DIM,
    EE_PROPRIO_DIM,
)
from .so101_env import OBS_KEY, SO101RobotEnv
from .wrappers import SO101RealWrapper
from .env_factory import SO101RealEnvArgs, make_so101_env

__all__ = [
    "SO101RobotEnv",
    "SO101RealWrapper",
    "SO101RealEnvArgs",
    "make_so101_env",
    "OBS_KEY",
    "STATE_DIM",
    "EE_PROPRIO_DIM",
    "ACTION_DIM",
    "MAX_DELTA_DEG",
    "MAX_DELTA_M",
    "MAX_EPISODE_STEPS",
    "CONTROL_FREQUENCY_HZ",
    "JOINT_NAMES",
    "JOINT_LOWER_DEG",
    "JOINT_UPPER_DEG",
    "HOME_POSITION_DEG",
    "HOME_EE_M",
    "HOME_GRIPPER_DEG",
    "EE_HALF_RANGE_M",
    "EE_LOWER_M",
    "EE_UPPER_M",
    "GRIPPER_HALF_RANGE",
    "GRIPPER_LOWER_DEG",
    "GRIPPER_UPPER_DEG",
    "DEFAULT_ROBOT_HOST",
    "DEFAULT_ROBOT_PORT",
]
