# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# Local copy for use in mpail2 env — imports from local services_pb2 instead of lerobot.
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mpail2.envs.real.so101.transport import services_pb2 as lerobot_dot_transport_dot_services__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__

try:
    from grpc._utilities import first_version_is_lower
    if first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION):
        warnings.warn(
            f'grpc {GRPC_VERSION} is older than generated code target {GRPC_GENERATED_VERSION}. '
            'Things may still work, but consider upgrading grpcio.',
            RuntimeWarning,
        )
except ImportError:
    pass


class AsyncInferenceStub(object):
    """Client stub for AsyncInference service."""

    def __init__(self, channel):
        self.SendObservations = channel.stream_unary(
            '/transport.AsyncInference/SendObservations',
            request_serializer=lerobot_dot_transport_dot_services__pb2.Observation.SerializeToString,
            response_deserializer=lerobot_dot_transport_dot_services__pb2.Empty.FromString,
        )
        self.GetActions = channel.unary_unary(
            '/transport.AsyncInference/GetActions',
            request_serializer=lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
            response_deserializer=lerobot_dot_transport_dot_services__pb2.Actions.FromString,
        )
        self.SendPolicyInstructions = channel.unary_unary(
            '/transport.AsyncInference/SendPolicyInstructions',
            request_serializer=lerobot_dot_transport_dot_services__pb2.PolicySetup.SerializeToString,
            response_deserializer=lerobot_dot_transport_dot_services__pb2.Empty.FromString,
        )
        self.Ready = channel.unary_unary(
            '/transport.AsyncInference/Ready',
            request_serializer=lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
            response_deserializer=lerobot_dot_transport_dot_services__pb2.Empty.FromString,
        )


class AsyncInferenceServicer:
    """AsyncInference: from Robot perspective
    Robot send observations to & executes action received from a remote Policy server
    """

    def SendObservations(self, request_iterator, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActions(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPolicyInstructions(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ready(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AsyncInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'SendObservations': grpc.stream_unary_rpc_method_handler(
            servicer.SendObservations,
            request_deserializer=lerobot_dot_transport_dot_services__pb2.Observation.FromString,
            response_serializer=lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
        ),
        'GetActions': grpc.unary_unary_rpc_method_handler(
            servicer.GetActions,
            request_deserializer=lerobot_dot_transport_dot_services__pb2.Empty.FromString,
            response_serializer=lerobot_dot_transport_dot_services__pb2.Actions.SerializeToString,
        ),
        'SendPolicyInstructions': grpc.unary_unary_rpc_method_handler(
            servicer.SendPolicyInstructions,
            request_deserializer=lerobot_dot_transport_dot_services__pb2.PolicySetup.FromString,
            response_serializer=lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
        ),
        'Ready': grpc.unary_unary_rpc_method_handler(
            servicer.Ready,
            request_deserializer=lerobot_dot_transport_dot_services__pb2.Empty.FromString,
            response_serializer=lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'transport.AsyncInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('transport.AsyncInference', rpc_method_handlers)
