# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# Local copy for use in both mpail2 and lerobot envs — imports from local
# so101_robot_pb2 instead of a bare top-level module.
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mpail2.envs.real.so101.transport import so101_robot_pb2 as so101__robot__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in so101_robot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SO101RobotStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Reset = channel.unary_unary(
                '/so101robot.SO101Robot/Reset',
                request_serializer=so101__robot__pb2.ResetRequest.SerializeToString,
                response_deserializer=so101__robot__pb2.RobotState.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/so101robot.SO101Robot/Step',
                request_serializer=so101__robot__pb2.StepRequest.SerializeToString,
                response_deserializer=so101__robot__pb2.RobotState.FromString,
                _registered_method=True)


class SO101RobotServicer:
    """Missing associated documentation comment in .proto file."""

    def Reset(self, request, context):
        """Move the arm to HOME_POSITION_DEG and open the gripper; returns the resulting state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Command a joint-position target; returns the state resulting from that action.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SO101RobotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=so101__robot__pb2.ResetRequest.FromString,
                    response_serializer=so101__robot__pb2.RobotState.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=so101__robot__pb2.StepRequest.FromString,
                    response_serializer=so101__robot__pb2.RobotState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'so101robot.SO101Robot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('so101robot.SO101Robot', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SO101Robot:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/so101robot.SO101Robot/Reset',
            so101__robot__pb2.ResetRequest.SerializeToString,
            so101__robot__pb2.RobotState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/so101robot.SO101Robot/Step',
            so101__robot__pb2.StepRequest.SerializeToString,
            so101__robot__pb2.RobotState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
