# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: so101_robot.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'so101_robot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11so101_robot.proto\x12\nso101robot\"\x0e\n\x0cResetRequest\"!\n\x0bStepRequest\x12\x12\n\njoints_deg\x18\x01 \x03(\x02\";\n\nRobotState\x12\x12\n\njoints_deg\x18\x01 \x03(\x02\x12\x0b\n\x03\x63\x61m\x18\x02 \x01(\x0c\x12\x0c\n\x04\x63\x61m2\x18\x03 \x01(\x0c\x32\x80\x01\n\nSO101Robot\x12\x39\n\x05Reset\x12\x18.so101robot.ResetRequest\x1a\x16.so101robot.RobotState\x12\x37\n\x04Step\x12\x17.so101robot.StepRequest\x1a\x16.so101robot.RobotStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'so101_robot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESETREQUEST']._serialized_start=33
  _globals['_RESETREQUEST']._serialized_end=47
  _globals['_STEPREQUEST']._serialized_start=49
  _globals['_STEPREQUEST']._serialized_end=82
  _globals['_ROBOTSTATE']._serialized_start=84
  _globals['_ROBOTSTATE']._serialized_end=143
  _globals['_SO101ROBOT']._serialized_start=146
  _globals['_SO101ROBOT']._serialized_end=274
# @@protoc_insertion_point(module_scope)
